### ISSUE TITLE
is there a shared stories feature in this?

### ISSUE THREAD

**Issue by seshubonam** [MartsTech/snapchat-clone#88]
does "group posts" feature mean shared stories?

**Comment by seshubonam** [comment]
also unable to deploy, version issues

**Comment by MartsTech** [comment]
> does "group posts" feature mean shared stories?

Hi, if my memory serves me right, I meant stories that can be seen by all users in the system. Not really a group, but I just wasn't interested in implementing it at the time.

**Comment by MartsTech** [comment]
> also unable to deploy, version issues

Yes, expo had breaking changes, which are not addressed here. I suggest either trying to update the project or initializing a brand new one and just copying the src folder inside.

**Comment by seshubonam** [comment]
thanks for the swift response.
